name: chap_chap
description: Prendre soin de ses cheveux sans se prendre la tête !

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.0.2+3020

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  app_tracking_transparency: ^2.0.2+1
  auto_size_text: ^3.0.0
  built_collection: ^5.1.1
  built_value: ^8.4.1
  chewie: ^1.4.0
  cloud_firestore: ^4.0.4
  cloud_functions: ^4.0.3
  cupertino_icons: ^1.0.4
  expandable: ^5.0.1
  easy_debounce: ^2.0.2+1
  firebase_app_check: ^0.1.2+3
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  firebase_storage: ^11.0.4
  firebase_messaging: ^14.2.6
  flutter_cupertino_datetime_picker: ^3.0.0
  # flutter_datetime_picker: ^1.5.1
  flutter_datetime_picker_plus: ^2.1.0
  flutter_html: ^3.0.0-alpha.6
  flutter_inappwebview: ^5.7.2+3
  flutter_launcher_icons: ^0.12.0
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^2.0.2
  flutter_widget_from_html_core: ^0.10.0
  font_awesome_flutter: ^10.0.0
  google_fonts: ^4.0.3
  html_unescape: ^2.0.0
  image_picker: ^0.8.4+4
  intl: ^0.18.0
  in_app_purchase: ^3.0.8
  json_path: ^0.4.0
  json_serializable: ^6.1.5
  mime_type: ^1.0.0
  page_transition: ^2.0.4
  photo_view: ^0.14.0
  equatable: ^2.0.3
  rxdart: ^0.27.3
  shared_preferences: ^2.0.12
  smooth_page_indicator: ^1.0.0+2
  styled_text: ^8.1.0
  table_calendar: ^3.0.8
  timeago: ^3.3.0
  url_launcher: ^6.1.10
  video_player: ^2.2.16
  wakelock_web: ^0.4.0
  webviewx: ^0.2.1
  excel: ^2.0.4
  flutter_switch: ^0.3.2
  flutter_rating_stars: ^1.0.3+4
  flutter_page_view_indicator: ^0.0.5
  cached_network_image: ^3.3.1

dev_dependencies:
  build_runner: ^2.3.3
  built_value_generator: ^8.4.1

  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_launcher_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/allRecettes.json
    - assets/fonts/
    - assets/images/
    - assets/shampoings/
    - assets/hydratants/
    - assets/nourissant/
    - assets/eau/
    - assets/leavein/
    - assets/gel/
    - assets/lotion/
    - assets/gommage/
    - assets/proteine/
    - assets/articles/
    - assets/audios/
    - assets/icons/
    - assets/
    - assets/lottie_animations/
    - assets/programmes/
    - assets/profil/

fonts:
  - family: Avenir Next Bold
    fonts:
      - asset: assets/fonts/AvenirNext-Bold.ttf
        weight: 700
  - family: Avenir Book
    fonts:
      - asset: assets/fonts/Avenir_Book.ttf
  - family: IBM
    fonts:
      - asset: assets/fonts/IBMPlexSerif-Thin.ttf
        weight: 100
      - asset: assets/fonts/IBMPlexSerif-ThinItalic.ttf
        weight: 100
        style: italic
      - asset: assets/fonts/IBMPlexSerif-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/IBMPlexSerif-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/IBMPlexSerif-Light.ttf
        weight: 300
      - asset: assets/fonts/IBMPlexSerif-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/IBMPlexSerif-Regular.ttf
      - asset: assets/fonts/IBMPlexSerif-Italic.ttf
        style: italic
      - asset: assets/fonts/IBMPlexSerif-Medium.ttf
        weight: 500
      - asset: assets/fonts/IBMPlexSerif-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/IBMPlexSerif-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/IBMPlexSerif-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/IBMPlexSerif-Bold.ttf
        weight: 700
      - asset: assets/fonts/IBMPlexSerif-BoldItalic.ttf
        weight: 700
        style: italic
